### ISSUE TITLE
find-previous goes forward when no selection

### ISSUE THREAD

**Issue by mark-hahn** [mark-hahn/find-selection#11]
find-previous goes forward when no selection.  This has probably been broken for a long time.

**Comment by kumarrishav** [comment]
@mark-hahn  is it same issue like what i observed.
when no selection, then ctrl+f3 (or ctrl+shift+f3 )will select the previous selection (what i did before) and go forward and previous accordingly

**Comment by mark-hahn** [comment]
Just to make sure we understand each other, this is how I repeat the
problem ...

- Select text that is in at least 3 places
- use `ctrl-f3` to select forward
- click in empty area to clear selection
- press `ctrl-shift-f3` and it will go forward when it is supposed to go
back

I should have put in these repeat instructions before.

A PR would be nice.  (grin)

**Comment by kumarrishav** [comment]
Ok, i can reproduce the issue. Will look into that. one more thing, if there is no selection then, why selection going forward and back

**Comment by mark-hahn** [comment]
It is very useful.  You can find something, change it and do other things,
and then find the next one.  I use it all the time.

**Comment by kumarrishav** [comment]
Yeah..you are right :)

**Comment by kumarrishav** [comment]
#13
