### ISSUE TITLE
Support for selecting the next instance

### ISSUE THREAD

**Issue by alanhogan** [mark-hahn/find-selection#3]
One thing I miss from Sublime is ⌘-Shift-G, which finds the next instance of the selected text *and selects it as well*, producing multiple selections.

![screen shot 2014-10-14 at 7 12 09 pm](https://cloud.githubusercontent.com/assets/6808/4639610/d09c903a-5410-11e4-943d-b70660e016ee.png)

⌘-Shift-G × 2 =

![screen shot 2014-10-14 at 7 12 01 pm](https://cloud.githubusercontent.com/assets/6808/4639611/d424edc4-5410-11e4-9f25-35786a0fbd1b.png)

I’m assuming this package doesn’t support that. I haven’t checked, but it wasn’t in the description.

Cheers.

**Comment by kumarrishav** [comment]
@mark-hahn  Here we are going to select the very next instance(or previous) or all the instance?

**Comment by mark-hahn** [comment]
Just add each selection one at a time as you search and find them.  There is already a package somewhere that selects all.  I personally don't think I'd use this but we aim to please. (grin)

Can you please check to see if @alanhogan's key selections are free using `search-all-keybindings`?

**Comment by kumarrishav** [comment]
@mark-hahn  ⌘-Shift-G .  I am unable to recognise the first key

**Comment by mark-hahn** [comment]
I don't remember which key is which in a Mac.  I think `⌘` is CMD which is ctrl on windows/linux.  You might google it.

**Comment by mark-hahn** [comment]
I'm closing this issue.   I was just reading the new atom manual and it says this feature is built into atom ...

```
cmd-D
Select the next word in the document that is the same as the currently selected
word
ctrl-cmd-G
Select all words in document that are the same as the one under the current
cursor(s)
```
