### ISSUE TITLE
Separate keybinding for select current & find?

### ISSUE THREAD

**Issue by dwelle** [mark-hahn/find-selection#4]
If you don't select anything and do `find-selection:find-next`, it might be useful to auto-select current word under caret. This is the bahaviour of [next-occurrence][YNuHdb] package, and what most other editors do, from my experience.

However, I think there's value in keeping both, so a separate keybinding would be great. Currently, I ended up using both packages at the same time. Downside of this is the packages don't share history, and if I search for a word using next-occurrence package, and then do `ctrl-f3` using yours, it doesn't share the last-word-searched.

[YNuHdb]: https://github.com/paradoxxxzero/next-occurrence

**Comment by mark-hahn** [comment]
Sorry for taking so long to respond.  I haven't forgotten this.  It is on my long to-do list.

**Comment by dwelle** [comment]
Cool, good to know.

**Comment by mark-hahn** [comment]
I decided against this.  A common operation is to click to remove a selection and then using the find with the last search string.  Adding this command would mean you couldn't select just anywhere to remove the selection.  It isn't that hard to double-click.

Let me know if you have counter-arguments.

**Comment by dwelle** [comment]
What you're describing could still work as expected, but there would just be two different keystrokes. One for, as you describe, would search for _last search string_, while a separate hotkey would first _select word beneath caret, and search next_  OR _search currently selected_.

To me, the best behavior would be if `find-selection:find-next` could be triggered via the same hotkey as default `find-next` (via `F3` or whatever's the default atom behavior), while your package's `find-selection:find-next` would either search for current selected word, or select-first, and then search. That way, you get the best out of the two worlds - and user can still use the default `F3` for finding next occurrence (which is probably burned into his muscle memory, anyway). Problem is, your package would have to talk to the default `Find → Find Next` (if that's  even possible), or overwrite it.

Either way, I'm surprised you suggest using double-click for word selection. Doesn't that disrupt your workflow _a_ bit (moving the hand to the mouse)? For this operation, I'm currently using a workflow which I'm not even gonna mention because you'd then be surprised why I'm suggesting this micro-optimization in the first place - but still I find great value in the suggested feature as it can greatly speed up your workflow in the long run (if you're willing to optimize, that is).

**Comment by mark-hahn** [comment]
Let me think about this ...

> Doesn't that disrupt your workflow *a* bit (moving the hand to the mouse)?

No, what disrupts my workflow is moving my hand to the keyboard.  I have my
mouse on the left and all interesting keys (cut/copy/save/find next, etc.)
mapped to key combos on the num keypad. One hand each. This is almost as
good as a chording keyboard.

**Comment by dwelle** [comment]
Yea, but when you're writing code, I guess you have both hands at the center of your keyboard, no?

**Comment by mark-hahn** [comment]
>  but when you're writing code, I guess you have both hands at the center
of your keyboard,

No, I use telepathy.  (grin)  Actually, when entering small amounts of text
I will use just my right hand.

I have never been able to learn VIM.  So I have to use the mouse all the
time anyway.  Using the arrow keys would be way too slow.

I've been kind of yanking your chain.  I have arthritis problems and I use
the mouse (big trackball) and keyboard in a strange way.

None of this has anything to do with considering your requests.  One thing
that bothers me is shipping so many keybindings.  So maybe I'll had more
commands for things like this and not ship a key binding for them.  You can
add your own.

**Comment by dwelle** [comment]
Sounds good.
