### ISSUE TITLE
Depreciated calls: Use activationCommands instead of activationEvents in package.json

### ISSUE THREAD

**Issue by kumarrishav** [mark-hahn/find-selection#7]
@mark-hahn I found this issue while working on this package. Please look, if this is really a issue. 
Thanks

**Comment by mark-hahn** [comment]
I've gotten that warning in several packages but when I just replace the words nothing works.  I don't know where docs for activationCommands are.  I'll ask on the forum.

**Comment by mark-hahn** [comment]
I tried using activationCommands but it is very broken so this is on hold.  https://discuss.atom.io/t/how-do-you-use-activationcommands-in-package-json/15414/2

**Comment by mark-hahn** [comment]
Fixed in 0.13.7
